from __future__ import annotations

import contextlib
import io
import tempfile
import unittest
from pathlib import Path

from scripts import build_shaders, gen_abi


GENERATED = """// Generated by gen_shader_abi from the 'probe' ABI schema - do not edit.
module gpu;

struct RootAbiMemberSpec @private {
    uint offset;
}

struct RootAbiSpec @private {
    RootAbiMemberSpec[1] members;
}

struct RootPush {
    GpuAddress root_gpu;
}
$assert RootPush::size == 8;

struct AccelerationStructureInstance {
    Vec4f transform_row_0;
    Vec4f transform_row_1;
    Vec4f transform_row_2;
    uint custom_index_and_mask;
    uint record_offset_and_flags;
    GpuAddress acceleration_structure;
}
$assert AccelerationStructureInstance::size == 64;
$assert $reflect(AccelerationStructureInstance.acceleration_structure).offset == 56;

const RootAbiSpec ROOT_PUSH_ABI @private = {
    .members = { {} },
};
$assert ROOT_PUSH_ABI.block_size == RootPush::size;
"""


class GenAbiTest(unittest.TestCase):
    def test_shader_stage_table_uses_one_glslc_toolchain(self) -> None:
        expected = {
            ".comp": "compute",
            ".vert": "vertex",
            ".frag": "fragment",
            ".rgen": "rgen",
            ".rmiss": "rmiss",
            ".rchit": "rchit",
            ".rahit": "rahit",
            ".rint": "rint",
            ".rcall": "rcall",
        }

        self.assertEqual(build_shaders.STAGES, expected)

    def test_ray_shader_headers_share_only_the_acceleration_structure_heap(self) -> None:
        root = Path(__file__).resolve().parent.parent
        shared = (root / "include/shaders/internal/acceleration_structure_heap.glsl").read_text()
        ray_query = (root / "include/shaders/ray_query.glsl").read_text()
        ray_tracing = (root / "include/shaders/ray_tracing.glsl").read_text()

        self.assertIn("layout(set = 0, binding = 5)", shared)
        self.assertIn("GPU_ACCELERATION_STRUCTURE_SLOT", shared)
        self.assertIn("GL_EXT_ray_query", ray_query)
        self.assertIn('internal/acceleration_structure_heap.glsl', ray_query)
        self.assertIn("GL_EXT_ray_tracing", ray_tracing)
        self.assertNotIn("GL_EXT_ray_query", ray_tracing)
        self.assertIn('internal/acceleration_structure_heap.glsl', ray_tracing)

    def test_splits_public_declarations_from_private_metadata(self) -> None:
        public, private = gen_abi.split_gpu_c3(GENERATED)

        self.assertIn("struct RootPush", public)
        self.assertIn("struct AccelerationStructureInstance", public)
        self.assertIn("AccelerationStructureInstance::size == 64", public)
        self.assertIn("AccelerationStructureInstance.acceleration_structure).offset == 56", public)
        self.assertNotIn("RootAbiSpec", public)
        self.assertIn("module gpu::internal @private;", private)
        self.assertIn("struct RootAbiMemberSpec @private", private)
        self.assertIn("const RootAbiSpec ROOT_PUSH_ABI @private", private)
        self.assertNotIn("struct RootPush {", private)

    def test_marked_block_detects_and_repairs_drift(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "gpu.c3i"
            path.write_text(
                "module gpu;\n\n"
                f"{gen_abi.PUBLIC_ABI_START}\nold\n"
                f"{gen_abi.PUBLIC_ABI_END}\n",
                encoding="utf-8",
            )

            with contextlib.redirect_stderr(io.StringIO()):
                self.assertFalse(gen_abi.sync_marked_block(
                    path,
                    gen_abi.PUBLIC_ABI_START,
                    gen_abi.PUBLIC_ABI_END,
                    "new\n",
                    True,
                ))
            self.assertTrue(gen_abi.sync_marked_block(
                path,
                gen_abi.PUBLIC_ABI_START,
                gen_abi.PUBLIC_ABI_END,
                "new\n",
                False,
            ))
            self.assertIn("\nnew\n", path.read_text(encoding="utf-8"))


if __name__ == "__main__":
    unittest.main()
