from __future__ import annotations

import contextlib
import io
import tempfile
import unittest
from pathlib import Path

from scripts import gen_abi


GENERATED = """// Generated by gen_shader_abi from the 'probe' ABI schema - do not edit.
module gpu;

struct RootAbiMemberSpec @private {
    uint offset;
}

struct RootAbiSpec @private {
    RootAbiMemberSpec[1] members;
}

struct RootPush {
    GpuAddress root_gpu;
}
$assert RootPush::size == 8;

const RootAbiSpec ROOT_PUSH_ABI @private = {
    .members = { {} },
};
$assert ROOT_PUSH_ABI.block_size == RootPush::size;
"""


class GenAbiTest(unittest.TestCase):
    def test_splits_public_declarations_from_private_metadata(self) -> None:
        public, private = gen_abi.split_gpu_c3(GENERATED)

        self.assertIn("struct RootPush", public)
        self.assertNotIn("RootAbiSpec", public)
        self.assertIn("module gpu::internal @private;", private)
        self.assertIn("struct RootAbiMemberSpec @private", private)
        self.assertIn("const RootAbiSpec ROOT_PUSH_ABI @private", private)
        self.assertNotIn("struct RootPush {", private)

    def test_marked_block_detects_and_repairs_drift(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "gpu.c3i"
            path.write_text(
                "module gpu;\n\n"
                f"{gen_abi.PUBLIC_ABI_START}\nold\n"
                f"{gen_abi.PUBLIC_ABI_END}\n",
                encoding="utf-8",
            )

            with contextlib.redirect_stderr(io.StringIO()):
                self.assertFalse(gen_abi.sync_marked_block(
                    path,
                    gen_abi.PUBLIC_ABI_START,
                    gen_abi.PUBLIC_ABI_END,
                    "new\n",
                    True,
                ))
            self.assertTrue(gen_abi.sync_marked_block(
                path,
                gen_abi.PUBLIC_ABI_START,
                gen_abi.PUBLIC_ABI_END,
                "new\n",
                False,
            ))
            self.assertIn("\nnew\n", path.read_text(encoding="utf-8"))


if __name__ == "__main__":
    unittest.main()
